[build-system]
requires = ["setuptools >= 42", "wheel", "setuptools_scm[toml]>=3.4"]
build-backend = "setuptools.build_meta"

[tool.setuptools_scm]
write_to = "src/alias/_version.py"

[tool.pytest.ini_options]
minversion = 6.0
addopts = "--cov src --cov-report html --cov-report term"
