name: Run Tests

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  python:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Set up Python 3.9
      uses: actions/setup-python@v2
      with:
        python-version: 3.9

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install flake8 tox setuptools_scm

    - name: Lint with flake8
      run: |
        # stop the build if there are Python syntax errors or undefined names
        flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics
        # exit-zero treats all errors as warnings. The GitHub editor is 127 chars wide
        flake8 . --count --exit-zero --max-complexity=10 --statistics

    - name: Test with tox
      run: |
        tox

  docker:
    needs: python
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Build the Docker container.
        run: |
          docker-compose build
          docker-compose run app alias-app add search https://www.google.com/

      - name: Check that it returns the correct redirects.
        run: |
          docker-compose up -d

          ./tests/check_response.sh search 301 https://www.google.com/
          ./tests/check_response.sh unknown 404 ""

          exit_code=0
          if [ -f "error_occurred" ]; then
              exit_code=1
          fi

          docker-compose down
          exit ${exit_code}
